esphome:
  name: athombulb3
  on_boot:
    - priority: 800
      then:
        - delay: 250ms
        - light.turn_on: 
            id: athombulb
            color_brightness: 0%
            white: 100%
            color_temperature: 4184K

esp8266:
  board: esp8285

web_server:
  port: 80

substitutions:
  friendly_name: "Smart Bulb 3"
  name: athombulb3
  static_ip: 192.168.2.145

wifi:
  ssid: !secret ssid
  password: !secret password
#  use_address: 192.168.2.145
 # output_power: 8.5dB
#  fast_connect: on
#  reboot_timeout: 0s
#  manual_ip:
#    static_ip: ${static_ip}
#    gateway: 192.168.2.1
 #   subnet: !secret subnet
 #   dns1: !secret dns1

captive_portal:
logger:
api:
ota:
  platform: esphome

output:
  - platform: esp8266_pwm
    id: red_output
    pin: GPIO4
    min_power: 0.000499
    max_power: 1
    zero_means_zero: true
  - platform: esp8266_pwm
    id: green_output
    pin: GPIO12
    min_power: 0.000499
    max_power: 1
    zero_means_zero: true
  - platform: esp8266_pwm
    id: blue_output
    pin: GPIO14
    min_power: 0.000499
    max_power: 1
    zero_means_zero: true
  - platform: esp8266_pwm
    id: white_output
    pin: GPIO5
    min_power: 0.01
    max_power: 0.9
    zero_means_zero: true
  - platform: esp8266_pwm
    id: ct_output
    inverted: true
    pin: GPIO13
    min_power: 0.01
    max_power: 0.9
    zero_means_zero: true

sensor:
  - platform: homeassistant
    entity_id: sensor.colorloopstate
    id: hassstate

light:
  - platform: rgbct
    id: athombulb
    restore_mode: ALWAYS_ON
    name: "${friendly_name}"
    red: red_output
    green: green_output
    blue: blue_output
    white_brightness: white_output
    color_temperature: ct_output
    cold_white_color_temperature: 6000K
    warm_white_color_temperature: 3000K
    color_interlock: true
    effects:
      - strobe:
          name: Music
          colors:
            - state: True
              brightness: 100%
              red: 0%
              green: 0%
              blue: 100%
              white: 0%
              duration: 100ms
              color_mode: RGB
            - state: True
              brightness: 100%
              red: 0%
              green: 100%
              blue: 100%
              white: 0%
              duration: 100ms
              color_mode: RGB
            - state: True
              brightness: 0%
              red: 0%
              green: 0%
              blue: 0%
              white: 0%
              duration: 100ms
              color_mode: RGB
            - state: True
              brightness: 100%
              red: 100%
              green: 0%
              blue: 100%
              white: 0%
              duration: 100ms
              color_mode: RGB
            - state: True
              brightness: 100%
              red: 0%
              green: 100%
              blue: 0%
              white: 0%
              duration: 100ms
              color_mode: RGB
            - state: True
              brightness: 100%
              red: 100%
              green: 0%
              blue: 0%
              white: 0%
              duration: 100ms
              color_mode: RGB
      - lambda:
          name: Color Loop
          lambda: |-
            static float state = 0;
            if (state != id(hassstate).state) {
              state = id(hassstate).state;
              auto call = id(athombulb).turn_on();
              call.set_transition_length(3000);
              if (state == 0) {
                call.set_rgb(0.45, 0.98, 0.39);
              } else if (state == 1) {
                call.set_rgb(0.45, 0.98, 0.93);
              } else if (state == 2) {
                call.set_rgb(0.38, 0.15, 0.96);
              } else if (state == 3) {
                call.set_rgb(0.5, 0.17, 0.96);
              } else {
                call.set_rgb(0.92, 0.2, 0.27);
              }
              call.perform();
            }
