substitutions:
  name: kauf-plug-8218eb
  sub_on_turn_on: script_off_timer
  sub_on_turn_off: script_timer_stop
  friendly_name: Straightener
  
packages:
  Kauf.PLF12-Base: github://KaufHA/PLF12/kauf-plf12.yaml

esphome:
  name: ${name}
  name_add_mac_suffix: false

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 0s

api:
  reboot_timeout: 0s

script:
  - id: script_off_timer
    then:
      - delay: 1200s
      - switch.turn_off: relay
  - id: script_timer_stop
    then:
      - switch.turn_off: relay
      - script.stop: script_off_timer