packages:
  Kauf.PLF10: github://KaufHA/PLF10/kauf-plug.yaml
  Kauf.PLF12-Base: github://KaufHA/PLF12/kauf-plf12-base.yaml

substitutions:
  name: kauf-plug-7aaad6
esphome:
  name: ${name}
  name_add_mac_suffix: false

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password